name: CI with Cache

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: prime-cache-716fc84
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-716fc84

      - name: Report cache result
        run: echo "Cache result: ${{ steps.cache.outputs.cache-hit }}"

      - name: Install dependencies
        run: pip install -r requirements.txt || echo "No requirements.txt found"
